import { getSupabaseClient, isSupabaseConfigured } from "../lib/supabaseClient";
import { validateSchoolEntry, type SchoolEntryDraft } from "../lib/geminiSchoolGeneratorEngine";
import type { SchoolEntry } from "../data/schoolsData";
import type { PitchTone } from "../types";

export interface GeminiOutreachRequest {
  athleteName: string;
  position: string;
  starRating: number;
  originState: string;
  tone: PitchTone;
  coachName: string;
  programName: string;
}

export interface GeminiOutreachResponse {
  draft: string;
}

export interface GeminiSchoolResponse {
  school: SchoolEntryDraft;
}

/**
 * Invokes `gemini-assistant` with the user JWT. The Gemini key never enters the SPA.
 */
export async function generateRecruitingOutreachDraft(
  payload: GeminiOutreachRequest,
): Promise<GeminiOutreachResponse> {
  if (!isSupabaseConfigured()) {
    throw new Error("Supabase is not configured. Cannot invoke gemini-assistant.");
  }

  const supabase = getSupabaseClient();
  const { data, error } = await supabase.functions.invoke<GeminiOutreachResponse>("gemini-assistant", {
    body: { action: "OUTREACH_DRAFT", ...payload },
  });

  if (error) {
    throw new Error(error.message);
  }
  if (!data?.draft?.trim()) {
    throw new Error("Empty draft from gemini-assistant.");
  }
  return { draft: data.draft.trim() };
}

/**
 * Uses Gemini AI via edge runtime to generate a structured, verified SchoolEntry object.
 */
export async function generateSchoolWithGemini(schoolQuery: string): Promise<SchoolEntry> {
  if (!isSupabaseConfigured()) {
    throw new Error("Supabase is not configured. Cannot invoke gemini-assistant.");
  }

  const supabase = getSupabaseClient();
  const { data, error } = await supabase.functions.invoke<GeminiSchoolResponse>("gemini-assistant", {
    body: { action: "GENERATE_SCHOOL", schoolQuery },
  });

  if (error) {
    throw new Error(error.message);
  }
  if (!data?.school) {
    throw new Error("Gemini AI failed to return school data.");
  }

  const validation = validateSchoolEntry(data.school);
  if (!validation.isValid || !validation.school) {
    throw new Error(validation.error || "Invalid school data generated by Gemini AI.");
  }

  return validation.school;
}
