import { mkdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import path from "node:path";
import type { FailureNode } from "./types.ts";

/**
 * Topological Failure Graph — persists nodes and synthesizes assertion guards.
 * Assertion bodies are JSON-compared expected values, never eval'd L2 templates.
 */
export class TopologicalFailureGraphSynthesizer {
  readonly graphStorePath: string;
  nodes: Record<string, FailureNode>;

  constructor(
    readonly repoRoot: string,
    graphStoreRelative = ".federov/failure_graph.json",
  ) {
    this.graphStorePath = path.join(repoRoot, graphStoreRelative);
    this.nodes = this.loadGraph();
  }

  private loadGraph(): Record<string, FailureNode> {
    if (!existsSync(this.graphStorePath)) {
      return {};
    }
    const raw = JSON.parse(readFileSync(this.graphStorePath, "utf8")) as Record<
      string,
      FailureNode
    >;
    return raw;
  }

  private saveGraph(): void {
    mkdirSync(path.dirname(this.graphStorePath), { recursive: true });
    writeFileSync(this.graphStorePath, `${JSON.stringify(this.nodes, null, 2)}\n`, "utf8");
  }

  registerAndSynthesize(node: FailureNode): string {
    if (!/^[A-Za-z0-9._-]+$/.test(node.nodeId)) {
      throw new Error(`Invalid failure node id: ${node.nodeId}`);
    }
    if (!node.testPath.startsWith("scripts/federov/guards/")) {
      throw new Error("Guard tests must live under scripts/federov/guards/");
    }

    this.nodes[node.nodeId] = node;
    this.saveGraph();

    const fullTestPath = path.join(this.repoRoot, node.testPath);
    mkdirSync(path.dirname(fullTestPath), { recursive: true });

    const expectedLiteral = JSON.stringify(node.assertionExpected);
    const expressionLiteral = JSON.stringify(node.assertionExpression);

    const testContent = `/**
 * AUTO-GENERATED BY FEDEROV TOPOLOGICAL FAILURE GRAPH SYNTHESIZER
 * Node: ${node.nodeId} | Category: ${node.category}
 * Rule: ${node.correctiveRuleId} — ${node.correctiveDescription}
 * Bad assumption: ${node.badAssumption.replace(/\*\//g, "* /")}
 */
import assert from "node:assert/strict";

const EXPRESSION = ${expressionLiteral} as const;
const EXPECTED = ${expectedLiteral} as unknown;

function evaluateAllowlisted(expression: string): unknown {
  switch (expression) {
    case "EPISTEMIC_HALT_THRESHOLD":
      return 0.4;
    case "REGVE_ALLOWLIST_HAS_LINT":
      return true;
    case "FAILURE_GRAPH_STORE_RELATIVE":
      return ".federov/failure_graph.json";
    default:
      throw new Error(\`Unknown allowlisted assertion expression: \${expression}\`);
  }
}

assert.equal(evaluateAllowlisted(EXPRESSION), EXPECTED);
console.log("[PASS] Topological Guard ${node.nodeId}");
`;

    writeFileSync(fullTestPath, testContent, "utf8");
    return fullTestPath;
  }
}
