/**
 * AUTO-GENERATED BY FEDEROV TOPOLOGICAL FAILURE GRAPH SYNTHESIZER
 * Node: Build.Epistemic.HaltThreshold.001 | Category: Build.Epistemic
 * Rule: FK-EPISTEMIC-001 — Halt when Re >= 0.40
 * Bad assumption: Epistemic halt threshold can be raised silently
 */
import assert from "node:assert/strict";

const EXPRESSION = "EPISTEMIC_HALT_THRESHOLD" as const;
const EXPECTED = 0.4 as unknown;

function evaluateAllowlisted(expression: string): unknown {
  switch (expression) {
    case "EPISTEMIC_HALT_THRESHOLD":
      return 0.4;
    case "REGVE_ALLOWLIST_HAS_LINT":
      return true;
    case "FAILURE_GRAPH_STORE_RELATIVE":
      return ".federov/failure_graph.json";
    default:
      throw new Error(`Unknown allowlisted assertion expression: ${expression}`);
  }
}

assert.equal(evaluateAllowlisted(EXPRESSION), EXPECTED);
console.log("[PASS] Topological Guard Build.Epistemic.HaltThreshold.001");
